completed two column layout-Bo Mercado
rbomercado/c0122-code-solutions pull request #20
Opened 2022-01-28 19:40 UTC by rbomercado

![image](https://user-images.githubusercontent.com/97006645/151610975-3831d206-b87e-4b72-a167-19cfbb8698ad.png)

2022-01-28 20:32 UTC, rbomercado commented
oops this is in progress still sorry!

2022-01-28 23:35 UTC, codingcodymiller requested changes
Hey Bo! Just submitting a review so that I know this is still in progress.

2022-02-02 08:14 UTC, rbomercado commented
Gotcha! Fixed hopefully all that was off so to speak!
![image](https://user-images.githubusercontent.com/97006645/152116851-55b30bb0-8f84-4402-b8a0-fb854bc7cb29.png)

2022-02-02 18:31 UTC, codingcodymiller requested changes
Hey Bo, I suggest you review `css-layout-classes` again, you seem to still not fully comprehend their usage and how they should be made. If you have questions on this, please reach out, I am happy to help.

2022-02-02 18:31 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
Is this supposed to be a `column-half` class? If so, its styling should only be `width: 50%`.

2022-02-02 18:31 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +        </div>
This should be one `column-half` element, since it takes up half the width of its row.

2022-02-05 22:08 UTC, rbomercado commented
![image](https://user-images.githubusercontent.com/97006645/152660376-6df4f063-5b9b-49f1-a6b3-fcbcf7f001ac.png)


updated!

2022-02-07 18:05 UTC, codingcodymiller requested changes

2022-02-07 18:05 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +    <div class="col-5">
`col-5` what? Is this meant to signify `column-fifth`? I would err on the side of being more descriptive with your class names.

2022-02-07 18:05 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +     <div class="row1">
`row1`? Why do you need an additional class for `row` elements? If you want slightly different b behavior for a particular row, you should make a class you can add **_in addition_** to the normal `row` class. So you would end up with something like `class="row some-other-class"` on the element instead. That way you can use the original `row` class and just augment it with whatever special behavior you are trying to do.

2022-02-09 04:53 UTC, thebearingedge requested changes
Ok, great. Just about done. No rush on these minor changes.

2022-02-09 04:53 UTC, thebearingedge commented on css-two-column-layout/styles.css
> +  padding-left: 30px;
Please remove this `padding-left`.

2022-02-09 04:53 UTC, thebearingedge commented on css-two-column-layout/styles.css
> +}
You can remove this if it's not being used.

2022-02-09 04:53 UTC, thebearingedge commented on css-two-column-layout/styles.css
> +}
Please remove any of these that aren't being used.

2022-02-09 06:19 UTC, rbomercado commented
updated selector properties and removed selectors that were not being used

2022-02-09 15:24 UTC, thebearingedge approved these changes

2022-02-09 18:10 UTC, merged