completed four column layout-Bo Mercado
rbomercado/c0122-code-solutions pull request #31
Opened 2022-02-03 01:05 UTC by rbomercado

![image](https://user-images.githubusercontent.com/97006645/152264050-c1a5644d-a484-4f23-a4b0-29f80a2e3ced.png)

2022-02-04 19:38 UTC, codingcodymiller requested changes
Hey Bo! The icons below the phone images are too large as compared to the example, please revise and submit a new screenshot with your revision.

2022-02-05 07:09 UTC, rbomercado commented
![image](https://user-images.githubusercontent.com/97006645/152632454-34d9ce90-0c5b-475d-a6d7-e325d65335e2.png)

2022-02-07 18:09 UTC, codingcodymiller requested changes

2022-02-07 18:09 UTC, codingcodymiller commented on css-four-column-layout/index.html
> +
Please remove all this empty space.

2022-02-07 18:09 UTC, codingcodymiller commented on css-four-column-layout/index.html
> +
Please remove all this empty space.

2022-02-07 18:09 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +.img1 {
This class could use a better name.

2022-02-07 18:09 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +.img2 {
This class could use a better name.

2022-02-09 05:00 UTC, thebearingedge approved these changes

2022-02-09 18:11 UTC, merged