completed js loops practice
rbomercado/c0122-code-solutions pull request #33
Opened 2022-02-04 15:31 UTC by rbomercado

![image](https://user-images.githubusercontent.com/97006645/152556418-832fdc26-aa52-49b3-8830-155465b30a58.png)

2022-02-04 20:54 UTC, codingcodymiller requested changes

2022-02-04 20:54 UTC, codingcodymiller commented on javascript-loops-practice/add-suffix-to-all.js
> +    suffixArray.push(words[i] += suffix);
This is making a change to the original array, which is not good. Instead, you should just use that original array to generate the new values, but leave the original intact.

2022-02-04 20:54 UTC, codingcodymiller commented on javascript-loops-practice/countdown.js
> +  while (number <= 10 && number >= 0) {
Why ten?

2022-02-07 18:30 UTC, codingcodymiller requested changes

2022-02-07 18:30 UTC, codingcodymiller commented on javascript-loops-practice/add-suffix-to-all.js
> +    suffixArray[i] = (words[i] += suffix);
The `+=` is still making a change to the original array. Make sure you are verifying that you fixed bugs before re-submitting.

2022-02-09 15:52 UTC, thebearingedge approved these changes

2022-02-09 15:52 UTC, thebearingedge commented on javascript-loops-practice/add-suffix-to-all.js
> +    suffixArray[i] = (suffixArray[i] += suffix);
This can be simplified a bit so you only need one line and it doesn't change your words array.

```js
suffixArray.push(words[i] + suffix);
```

2022-02-09 15:53 UTC, thebearingedge requested changes
Sorry, I meant to request changes. please see my comment
https://github.com/rbomercado/c0122-code-solutions/pull/33/files#r802813830

2022-02-09 19:17 UTC, thebearingedge approved these changes
👍

2022-02-09 23:35 UTC, merged