comp string man 1-Bo Mercado
rbomercado/c0122-code-solutions pull request #38
Opened 2022-02-07 05:49 UTC by rbomercado

![image](https://user-images.githubusercontent.com/97006645/152731676-93871025-8d4e-4635-b744-80c01da5ddd0.png)

2022-02-07 05:49 UTC, rbomercado commented
![image](https://user-images.githubusercontent.com/97006645/152731701-aa512225-a898-4f33-93dd-6030f8f60b86.png)

2022-02-07 20:32 UTC, codingcodymiller requested changes
Hey Bo, it looks like you still have one test failing, please get that fixed.

2022-02-09 15:59 UTC, thebearingedge requested changes

2022-02-09 15:59 UTC, thebearingedge commented on string-manipulation-1/src/is-lower-cased.js
> +  }
Try doing this without the loop. Your `if` statement is already solving the problem.

2022-02-09 15:59 UTC, thebearingedge commented on string-manipulation-1/src/is-upper-cased.js
> +  }
Same here

2022-02-09 15:59 UTC, thebearingedge commented on string-manipulation-1/src/is-vowel.js
> +  }
If you make the character lowercased first, one time, then you can check half as many comparisons.

```js
var lowerChar = char.toLowerCase();
```

Also please try this without the loop.

2022-02-09 18:25 UTC, rbomercado commented
![image](https://user-images.githubusercontent.com/97006645/153265584-2076e7d1-5960-4720-8a5a-bd54ea48dead.png)

2022-02-09 19:18 UTC, thebearingedge approved these changes

2022-02-09 23:37 UTC, merged